services:
  server:
    build: ./server
    container_name: server_container_quic
    networks:
      net:
        ipv4_address: 10.10.20.5 
    expose:
      - 8080
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./server_output:/app/output:w


  client:
    build: ./client
    container_name: client_container_quic
    networks:
      net:
        ipv4_address: 10.10.20.7
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  pumba_delay:
    image: gaiaadm/pumba
    container_name: pumba_delay_quic
    depends_on:
      - client
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true 
    command: >
      netem --duration 60s --interface eth0 delay --time 100 --jitter 50 client_container_quic server_container_quic

  pumba_loss:
    image: gaiaadm/pumba
    container_name: pumba_loss_quic
    depends_on:
      - client
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true 
    command: >
      netem --duration 60s --interface eth0 loss --percent 90 client_container_quic server_container_quic



networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.20.0/24