services:
  server:
    build: ./server
    container_name: server_container
    networks:
      net:
        ipv4_address: 10.10.10.5 
    expose:
      - 8080
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./server_output:/app/output:w


  client:
    build: ./client
    container_name: client_container
    networks:
      net:
        ipv4_address: 10.10.10.7
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  pumba:
    image: gaiaadm/pumba
    container_name: pumba
    depends_on:
      - client
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
        netem --duration 60s --interface eth0 delay --time 100 --jitter 20 client_container server_container
 

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24